# Generated by Django 5.1.6 on 2025-03-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], default='one-time', max_length=20),
        ),
    ]
