# Generated by Django 5.2 on 2025-04-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0005_donation_is_amount_modified_donation_original_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Credit/Debit Card'), ('cash', 'Cash')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('lifetime', 'Lifetime')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
