services:
  - type: web
    name: donation-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn donation_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: donation-postgres-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: donation-postgres-db
    databaseName: donation_db
    plan: free
    ipAllowList: [] 